### ISSUE TITLE
Print whole reject file on tap test failure

### ISSUE THREAD

**Issue by locker** [tarantool/test-run#102]
Currently, only 10 last lines are printed (although test-run says 15 :-), which makes it impossible to investigate a failure in case the failed sub-test is not the last one. For instance, the output below doesn't give us a clue what happened here:
```
app-tap/tarantoolctl.test.lua                                   [ fail ]
Test failed! Last 15 lines of the result file:
    1..6
    ok - check 'start' command status for 'filler'
    ok - check lsn before
    ok - execution result
    ok - check lsn after
    ok - execution result
    ok - check lsn after
    # fill and test play output: end
ok - fill and test play output
# failed subtest: 1
```
That said, test-run must print the whole reject file produced by a failed tap test, because every its line may contain important information.

The issue blocks investigation of https://github.com/tarantool/tarantool/issues/3557

**Comment by Totktonada** [comment]
Most usual case is (I think) when the last lines gives necessary diagnostics. I would implement #90 instead of this issue to help investigating failures that reproduces only in Travis-CI or very rarely.

**Comment by locker** [comment]
> Most usual case is (I think) when the last lines gives necessary diagnostics.

That's simply not true. For instance, take app-tap/tarantoolctl.test.lua - unless it's one of the last 6 sub-tests that fails, the last 10 lines will always be the same.

> I would implement #90 instead of this issue to help investigating failures that reproduces only in Travis-CI or very rarely.

Why "instead"? Why not "along with"? Do you have any actual reason in mind why test-run shouldn't print the whole tap test output in case of failure? IMO the more information we have, the better. Besides, fixing this issue seems to be much easier than implementing #90.

**Comment by Totktonada** [comment]
> That's simply not true.

If so, it is worth to do.

**Comment by Totktonada** [comment]
@sergw Can you catch this issue?

**Comment by sergw** [comment]
Currently 10 lines of code for client part, and 15 for server part. They are hardcoded and should be configurable. We can add the behaviour to output whole results by enabling two parameters `--verbose` plus non empty metavar test. Also `--verbose` will be added as env (for `make test` cmd).

**Comment by locker** [comment]
Let's always print the whole tap result file. I don't see any point in making it configurable. We print the whole diff between .reject and .result for non-tap tests in case of failure. Why should we limit output of tap tests?
