### ISSUE TITLE
Disable reproduce trace for sql-tap/ tests

### ISSUE THREAD

**Issue by Korablev77** [tarantool/test-run#113]
It seems that each of sql-tap/ tests run with brand new Tarantool instance, so it makes no sense to display reproduce sequence for them.

**Comment by Totktonada** [comment]
I propose to add an option to suite.ini. Possible name: `show_reproduce_content = True|False` (default: `True`).

**Comment by Totktonada** [comment]
@Korablev77 This is test-run repository, not tarantool. Here we add the option, then one will use it for sql-tap suite in the tarantool repository.
