### ISSUE TITLE
Allow to run tests in specific order

### ISSUE THREAD

**Issue by locker** [tarantool/test-run#120]
The only reason why I need to use `./test-run.py -j -1` is that it runs tests in the same order they are specified in the arguments. Without `-j -1` I can only do that with `--reproduce`, but that's not really convenient, because I have to create a reproduce file then.

I think we should introduce a new option, say `--no-randomize`, which would make test-run run tests in exactly the same order they are specified in the arguments. Then we could drop all the code related to `-j -1` altogether.

**Comment by Totktonada** [comment]
We need to elaborate how this will work with multiple workers. Maybe we need to introduce `--reproduce=args` to run tests in specified order within one worker.

@locker What do you think about that?

**Comment by locker** [comment]
> We need to elaborate how this will work with multiple workers. Maybe we need to introduce `--reproduce=args` to run tests in specified order within one worker.

I don't really care whether it'll work for multiple workers or not. I'd be OK with me if this option only worked for single worker runs.

`--reproduce` option is already in use. Reusing it for this purpose would be confusing IMO. I'd rather add a bool option that would disable reordering.
