### ISSUE TITLE
Add command line option to disable reproducing trace

### ISSUE THREAD

**Issue by Korablev77** [tarantool/test-run#122]
Proposal is to add an option to be able to turn off reproducing trace: sometimes it consists of quite long list of tests and makes output unclear and complicated to read.

**Comment by sergw** [comment]
Temporarily, this command can be used as a workaround:
```
find . -name suite.ini | xargs sed -i '/^show_reproduce_content =/{h;s/=.*/= False/};${x;/^$/{s//show_reproduce_content = False/;H};x}'
```

**Comment by Totktonada** [comment]
Is any problem remains? We [implemented](https://github.com/tarantool/test-run/pull/116) `show_reproduce_content` option and [enabled](https://github.com/tarantool/tarantool/commit/e96cd176030b8c8282458b7bf9ef1817d05c0ccd) it for sql-tap test suite.

**Comment by Totktonada** [comment]
Feel free to reopen if you still experience any problems regarding this kind of test-run's output.
