### ISSUE TITLE
update tarantool-python connector

### ISSUE THREAD

**Issue by kbelyavs** [tarantool/test-run#126]
Some kind of loop:
Test-run depends on tarantool-python connector. In attempt to test with test-run tarantool-python itself, I got an error due to API mismatch, since test-run self imports relatively old connector parts.

One of possible solutions is to update connector version to match latest API.

**Comment by sergw** [comment]
It is good to show the steps how to reproduce the error. And environment:
- `test-run` branch
- `tarantool` branch
- OS version

**Comment by Totktonada** [comment]
@sergw It was observed in the scope of https://github.com/tarantool/tarantool-python/pull/109 when we try to use test-run to test the connector (not tarantool).
