### ISSUE TITLE
Create or update result files only under an option

### ISSUE THREAD

**Issue by Totktonada** [tarantool/test-run#194]
Implicit generation of new result files may be unexpected behaviour, see https://github.com/tarantool/tarantool/issues/4258 (proposed by @avtikhon).

Aside of that, manual updating of result files is not always convenient, see https://github.com/tarantool/tarantool/issues/4654 (proposed by @cyrillos).

I filed this issue against this repository to ease track of work on this feature.

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH v2] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016853.html

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH v3 0/2] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/017522.html
