### ISSUE TITLE
Extend grep_log for crashed instances

### ISSUE THREAD

**Issue by OKriw** [tarantool/test-run#196]
At the moment we use grep_log to search patterns in instance log. It works fine if instance is alive. 
However, when flag crash_expected = True is set, and we need to search smth in crashed instance log, one needs to open, read end etc. 
i think it would be quite natural if grep_log will be able to do it.

**Comment by Totktonada** [comment]
Example of usage of this functionality can be found here: https://github.com/tarantool/tarantool/commit/54606356501ae8d7e1dfe37ea48d580ab1e9b1cd.
