### ISSUE TITLE
[10sp] Make test (and other python code) Python3 compatible

### ISSUE THREAD

**Issue by kostja** [tarantool/test-run#20]
Python3 is the next major version and some Linux distros (e.g. Linux Arch) are already use it as a default. It makes sense to make the code python3 compatible. In theory conversion should be simple especially if you use tools like py2to3.

Moved from https://github.com/tarantool/tarantool/issues/56

**Comment by anatol** [comment]
Python2 is EOL. Python3 is a default version at major OS distributions. Could you please prioritize this effort and make tarantool project python2-free?

**Comment by ligurio** [comment]
I would try to decompose ticket to subtasks:
- [ ] remove relative module imports
- [ ] fix module imports for modules changed in Python 3 (for example ConfigParser)
- [ ] fix printing to make it compatible with 2 and 3 versions
- [ ] support Python 3 in Tarantool tests

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH v1] Support to run tests with Python 3
https://lists.tarantool.org/pipermail/tarantool-patches/2020-November/020872.html
