### ISSUE TITLE
Use LD_LIBRARY_PATH/LD_PRELOAD_LIBS

### ISSUE THREAD

**Issue by bigbes** [tarantool/test-run#21]
instead of copying .so/.dylib files

**Comment by Totktonada** [comment]
We just set `LUA_CPATH`, if it is about Lua modules written in C:

https://github.com/tarantool/test-run/blob/cb5adde9d399bdf478082a061739b78647752c85/lib/__init__.py#L59

If it is about some other problem, it requires clarification.

Feel free to reopen if I missed something.
