### ISSUE TITLE
Investigate whether it is possible to restart an instance within each worker queue

### ISSUE THREAD

**Issue by avtikhon** [tarantool/test-run#215]
Measure full test suite with different threads count, say: 1, 8, 16, 32, 64.

**Comment by avtikhon** [comment]
Mistakenly committed to master - fixed by removing commit.

**Comment by avtikhon** [comment]
With server restart:
real	6m13,876s
user	23m25,039s
sys	6m16,945s

W/o server restart:
real	6m1,496s
user	17m11,663s
sys	3m38,423s

**Comment by Totktonada** [comment]
@avtikhon What hardware (at least CPU count), how much parallel jobs, which set of tests?

**Comment by avtikhon** [comment]
New way to restart server in test-run showed time differences:
```
off:

160:
real    3m43.669s
user    9m4.533s
sys     2m55.362s

16:
real    4m6.062s
user    6m10.191s
sys     1m42.741s

1:
real    12m55.112s
user    5m10.346s
sys     1m30.498s

on:

160:
real    4m4.583s	+8.6%
user    11m12.715s	+14%
sys     4m13.593s	+30%

16:
real    4m9.653s	+2%
user    7m4.913s	+21%
sys     2m16.460s	+24%

1:
real    14m40.410s	+12%
user    5m50.021s	+11%
sys     1m55.229s	+22%
```
