### ISSUE TITLE
Test_run:wait_upstream/downstream fail when `box.info.replication` is empty or not defined yet

### ISSUE THREAD

**Issue by Gerold103** [tarantool/test-run#221]
`box.info.replication` can be an empty table if the instance didn't start yet. I guess even `box.info` may be not defined, if `box.cfg` wasn't called, but the admin console was started. `Test_run.lua` has some functions assuming `box.info.replication` is not empty, and even contains the needed ID. They fail with an exception when it is not so, and I am forced to write `wait_cond` to wait for `box.info.replication[id]` before doing `wait_upstream/wait_downstream`. It does not look right.

**Comment by Totktonada** [comment]
Looks similar to eee42cbdbffe36fc206f4e81688bf1b49586475a, but now an entry in `box.info.replication` is not exist (or even `box.info`). Thanks for the notice!
