### ISSUE TITLE
create server <name> with work_dir=<path>

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#23]
I have pre-generated snapshot and xlog files from old versons of Tarantool. I would like to start a new instance of tarantool using my files:

    test_run:cmd('create server migration with script="xlog/migration.lua" workdir="xlog/migration/1.6.4"')

**Comment by Sulverus** [comment]
Done. Working example:
```lua
test_run = require('test_run')  
inspector = test_run.new()

inspector:cmd('create server migration with script="xlog/migration.lua", workdir="xlog/migration/1.6.4"')
inspector:cmd('start server migration')
inspector:cmd('switch migration')
```

**Comment by Sulverus** [comment]
merged
