### ISSUE TITLE
Implement ability to get test-run timeouts from the hosts local configurations

### ISSUE THREAD

**Issue by avtikhon** [tarantool/test-run#258]
Trying to fix #251 found that on old hosts vinyl/ suite tests failed to finish in default timeout '--test-timeout' == 110 seconds. Also it happened because of slow IO with slow hard drives setup on hosts. In major it happened on box.snapshot() calls, but could happen on any other commands.
To fix it was decided to collect statistics and setup on hosts local timeout configurations.
Found that running in complete parallel mode for all the tests even from fragile lists then test-timeout value had results:
  110 (default) -> a lot of fails
  210 -> fails rare, but still exists in different places, a lot of checksums needed to pass
  310 -> fails very rare, exists in a few places only, small number of checksums may help to pass it

**Comment by Totktonada** [comment]
I would not implement per-host timeouts until we'll find a reason to do so. I guess common timeouts for all workers is the way to go.

Anyway, from the test-run side we should only pick up values from the environment variables, nothing more.
