### ISSUE TITLE
start/stop instances with tarantoolctl

### ISSUE THREAD

**Issue by kostja** [tarantool/test-run#3]
Use tarantoolctl to prepare instance directories, start and stop instances, not the custom stuff in Python created before tarantoolctl came to exist.

**Comment by Sulverus** [comment]
Done. Please review
1. start with tarantoolctl with background=false
2. tarantoolctl updated to use local directory configuration
3. old test cases in tarantool updated
4. valgrind and gdb mixins updated

**Comment by Sulverus** [comment]
Reviewed with @rtsisyk, updated CMakeLists for ctl config. Merged.
