### ISSUE TITLE
Can't mkdir /var/lib/tarantool/vinyl: Permission denied

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#33]
```
/usr/bin/tarantoolctl: Starting instance...
/usr/bin/tarantoolctl: mkdir /mnt/data/data/work/tarantool/xx/test/var/vinyl
/usr/bin/tarantoolctl: mkdir /var/lib/tarantool/vinyl
/usr/bin/tarantoolctl: Can't mkdir /var/lib/tarantool/vinyl: Permission denied
```

Steps to reproduce:
1. Clone Tarantool 1.7, but don't build it (rm -f ./src/tarantool)
2. Install Tarantool 1.6.8 from packages and ensure that /usr/bin/tarantoolctl from 1.6.8 is present
3. cd test && ./test-run.py vinyl/
4. tail -f var/vinyl.log

**Comment by Totktonada** [comment]
It seems, it is not more the relevant: 1.6 and 1.7 are not supported anymore.
