### ISSUE TITLE
Option to disable test auto-rerun

### ISSUE THREAD

**Issue by Gerold103** [tarantool/test-run#334]
It complicates investigation of failure artifacts - rerun just creates more of them making it hard to find needed info.

**Comment by NickVolynkin** [comment]
Should this option disable auto-rerun for all tests, including those marked as fragile?

There's also a request for setting the amount of re-runs with an env variable and/or command line option.
A solution for both request could look something like this.

```bash
# disable auto-rerun
./test-run --rerun 0
# disable auto-rerun for fragile tests as well
./test-run --rerun-force 0
```
---


Follow-up to #328

**Comment by NickVolynkin** [comment]
@Gerold103 besides the CLI option, would you find it useful to set a system-wide config with "don't ever rerun tests on my machine"? Say, in the `~/.testrunrc` file:

```toml
retry=0
 ```

**Comment by Gerold103** [comment]
For me it would be enough to have a command line option which disables all auto-reruns, including fragile tests.
