### ISSUE TITLE
Add logging to test-run

### ISSUE THREAD

**Issue by feldsherov** [tarantool/test-run#34]
Create log of test-run operations, such start/stop/restart server, crash detects e.t.c

**Comment by Totktonada** [comment]
The `color_log()` function was introduced in the squshed commit b42093abc0e7fe895ff0ac7c0685d016c783b3a1 (sorry about this, now I would complain against squashing) and the start/stop/cleanup events are logged. The recent PR #237 adds more log events. I would consider the issue as resolved.

If we'll need to log more events, it is easy to add them.
