### ISSUE TITLE
Integrate with submodule tests

### ISSUE THREAD

**Issue by kostja** [tarantool/test-run#4]
I would like to extract libsmall (src/lib/small) into an own github project.
However, testing of libsmall is part of Tarantool integration suite, i.e. its unit tests. 
So I would like to move libsmall unit tests into libsmall (naturally). I still want to be able to run these
tests ouf of the main test suite, or at least be able to hook them up into the main suite. 

We may benefit from this option by hooking up sophia tests into the main test suite as well.

**Comment by bigbes** [comment]
I believe this was fixed
