### ISSUE TITLE
Add support for marking tests as flaky

### ISSUE THREAD

**Issue by racktear** [tarantool/test-run#43]
There should be a file listing all tests currently considered as flaky.
Flaky tests should produce warnings, but don't break builds.

**Comment by rtsisyk** [comment]
https://github.com/tarantool/tarantool/issues?q=is%3Aopen+is%3Aissue+label%3A%22flaky+test%22
We plan to fix all flaky tests in 1.7.4/1.7.5 and enable mandatory Travis CI/Hudson checks for all pushes. There is no need to mark tests as flaky in test-run in order disable it.
