### ISSUE TITLE
Enable parallel test-run by default for parallel suites

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#56]

**Comment by rtsisyk** [comment]
See  ca460403551522b34e162e8d04fff5a26170bfff

**Comment by Totktonada** [comment]
It’s implemented in test-run and pushed into test-run’s master, but on tarantool side it resides on @bigbes’es branch [real-parallel-test-run](https://github.com/tarantool/tarantool/tree/real-parallel-test-run). (Blocked by [#2436](https://github.com/tarantool/tarantool/issues/2436)?) @rtsisyk, do you want more info?

**Comment by rtsisyk** [comment]
Pushed
