### ISSUE TITLE
Enable per-suite test run w/ make

### ISSUE THREAD

**Issue by kyukhin** [tarantool/test-run#59]
It'll be useful (for out of source builds) to make it possible to run single suite w/ make command from build directory.

Say we have N suites: suite1, ... suiteN

Then we may refactor Makefile generator to contain following rules:
```
test-suite1: ...
...
test-suiteN:...
test: test-suite1 ... test-suiteN
```

which will allow to run selected suites w/ make:
`make test-sql-tap`

**Comment by bigbes** [comment]
It shouldn't belong here. You already can do `./test-run.py test-sql-tap`, so it's the matter of CMake scripts in Tarantool.

Superseeded by https://github.com/tarantool/tarantool/issues/2463
