### ISSUE TITLE
Add a global filter to ignore line numbers in error() output

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/test-run#9]
I have to update thousands lines in result files each time I change the single line in Lua:

```
 ...
 t:update()
 ---
-- error: '[string "-- tuple.lua (internal file)..."]:231: Usage: tuple:update({ {
+- error: '[string "-- tuple.lua (internal file)..."]:205: Usage: tuple:update({ {
     op, field, arg}+ })'
 ...
 t:update(10)
 ---
-- error: '[string "-- tuple.lua (internal file)..."]:231: Usage: tuple:update({ {
+- error: '[string "-- tuple.lua (internal file)..."]:205: Usage: tuple:update({ {
     op, field, arg}+ })'
 ...
 t:update({})
```

Please add a global filter for *.result files to replace `[string "-- * (internal file)..."]:(\d+):` with `[string "-- tuple.lua (internal file)..."]::`!

**Comment by kostja** [comment]
Roman, this must be done on the server side, error messages should not have
these numbers.

**Comment by rtsisyk** [comment]
ok, we have updated all tests instead.
